let suggestions = [
    "Ahmad Fausan Arif Hakim",
    "Ahmad Sibgatulah Latif",
    "Ardian Arya Putra",
    "Bayu Bagskara",
    "Bintang Riski Sulistio",
    "Hafis Alfitrah",
    "Muhammad Alamsyah",
    "Muhammad Risqi",
    "Vlogger",
    "Vechiles",
    "Facebook",
    "Freelancer",
    "Facebook Page",
    "Designer",
    "Developer",
    "Web Designer",
    "Web Developer",
    "Login Form in HTML & CSS",
    "How to learn HTML & CSS",
    "How to learn JavaScript",
    "How to become Freelancer",
    "How to become Web Designer",
    "How to start Gaming Channel",
    "How to start YouTube Channel",
    "What does HTML stands for?",
    "What does CSS stands for?",
];
